name: Run cucumber test

on:
  push:
    branches: ["main"]

jobs:
  test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/steup-java@v3
        with:
          java-version: "17"
          cache: maven
          distribution: "temurin"
      - uses: browser-actions/steup-chrome@latest
      - run: mvn clean test
